const starterEntries = [
  { date: '2026-09-22', category: 'Work & Study', title: 'Mendapat akses beta Android TISCO Task', body: 'Akses beta Android menjadi tanda bahwa project Task Reminder mulai terasa nyata. Peran saya sebagai PIC semakin jelas: menjaga requirement, backlog, dependensi, dan komunikasi tetap bergerak.', tags: ['TISCO', 'beta', 'project management'], win: 'Mendapat akses beta untuk mencoba alur aplikasi.', lesson: 'Project berkembang lebih rapi saat keputusan dan follow-up dicatat.' },
  { date: '2026-09-21', category: 'Work & Study', title: 'Memahami peran sebagai Project PIC', body: 'Saya mulai melihat pekerjaan PM bukan hanya membuat Gantt Chart. Saya perlu menjaga requirement, status, keputusan, dependency, dan pertanyaan client agar semua orang memiliki arah yang sama.', tags: ['PM', 'TISCO', 'reporting'], win: 'Peran dan tanggung jawab saya makin jelas.', lesson: 'Kejelasan scope membantu mencegah pekerjaan melebar.' },
  { date: '2026-09-16', category: 'Work & Study', title: 'Menyatukan FSD, MoM, dan Scope of Work', body: 'Saya membaca FSD lalu membandingkannya dengan hasil meeting dan Scope of Work. Dari sana saya menyiapkan daftar pertanyaan untuk Pak Nyoman dan melihat bagian yang masih perlu dipastikan.', tags: ['FSD', 'MoM', 'scope'], win: 'Berani mengubah kebingungan menjadi pertanyaan yang terstruktur.', lesson: 'Dokumen bukan sekadar formalitas; ia menyimpan keputusan project.' },
  { date: '2026-09-09', category: 'Work & Study', title: 'Mulai mendalami TISCO dan Lensa Bisnis', body: 'Pembahasan TISCO/Lensa Bisnis membuka banyak istilah dan alur baru: mockup, master data, synchronization, read-only, push notification, dan KPI. Rasanya banyak, tetapi ini awal memahami produk secara utuh.', tags: ['TISCO', 'learning', 'requirement'], win: 'Mulai membangun kosakata kerja di dunia produk.', lesson: 'Tidak harus langsung paham semuanya; penting mencatat dan menghubungkan konsepnya.' },
  { date: '2026-09-22', category: 'Business', title: 'Merancang Roblox MCP Trading System', body: 'Ide Roblox UGC berkembang dari trading manual menjadi rancangan sistem: inventory management, pengelompokan item, holding period, harga dan volume, strategi, ROI/profit, paper trading, serta integrasi website dan AI/MCP. Tahap awalnya tetap read-only sebelum automasi transaksi.', tags: ['Roblox UGC', 'MCP', 'trading system'], win: 'Mampu melihat minat sebagai sistem yang bisa dibangun.', lesson: 'Strategi perlu divalidasi dengan data dan paper trading sebelum diotomasi.' },
  { date: '2026-09-20', category: 'Reflection', title: 'Belajar melihat AI sebagai sistem, bukan sekadar chatbot', body: 'Diskusi dengan ChatGPT membawa alur pemikiran baru: AI terhubung ke API, database, backend, MCP, automation, sampai autonomous system. Saya juga mulai mengeksplorasi Linear, Figma, GitHub, dan kemungkinan AI agent untuk bisnis.', tags: ['AI', 'API', 'database', 'automation'], win: 'Cara berpikir mulai bergeser dari memakai AI ke membangun sistem dengan AI.', lesson: 'Value muncul ketika AI terhubung ke data dan workflow yang nyata.' },
  { date: '2026-09-20', category: 'Business', title: 'Mengeksplorasi AI Solar/PLTS Calculator', body: 'Saya memikirkan produk yang membaca tagihan listrik, memperkirakan konsumsi dan kebutuhan PLTS, menghitung investasi, penghematan, payback period, lalu menghasilkan proposal otomatis.', tags: ['PLTS', 'AI', 'business idea'], win: 'Menemukan masalah bisnis nyata yang dapat dibantu AI.', lesson: 'Ide bisnis kuat jika masalah, data, dan hasil untuk pengguna jelas.' },
  { date: '2026-09-22', category: 'Personal', title: 'Mendaftar Devpost LaunchHacks V dan mencari teammate', body: 'Saya mengambil langkah untuk masuk ke lingkungan membangun produk yang lebih aktif dengan mendaftar hackathon dan mulai mencari rekan satu tim.', tags: ['Devpost', 'hackathon', 'network'], win: 'Mulai membuka peluang kolaborasi.', lesson: 'Belajar membangun juga berarti belajar bertemu dan bekerja dengan orang lain.' },
  { date: '2026-08-21', category: 'Business', title: 'Menaruh perhatian pada Roblox UGC dan bisnis digital', body: 'Saya mulai melihat Roblox UGC sebagai ruang untuk belajar kreativitas dan bisnis digital, bukan hanya bermain. Ini menjadi salah satu arah yang ingin terus saya eksplorasi.', tags: ['Roblox UGC', 'business', 'creative'], win: 'Memandang minat sebagai kemungkinan karya dan bisnis.', lesson: 'Eksperimen kecil bisa menjadi pintu ke arah yang lebih besar.' }
];
const goals = [
  { title: 'Menjadi PIC TISCO yang lebih terstruktur', note: 'Memahami requirement, follow-up, dan timeline.', progress: 68 },
  { title: 'Membangun fondasi bisnis digital', note: 'Mengeksplorasi Roblox UGC dengan lebih serius.', progress: 35 },
  { title: 'Mencatat perjalanan hidup secara konsisten', note: 'Minimal satu refleksi bermakna setiap minggu.', progress: 50 }
];
let entries = JSON.parse(localStorage.getItem('farrell-journal-entries') || 'null') || starterEntries;
entries.forEach((entry, index) => { if (!entry.id) entry.id = `entry-${Date.now()}-${index}`; });
const $ = s => document.querySelector(s);
const formatDate = date => new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'}).format(new Date(date+'T00:00:00'));
const dayParts = date => { const d=new Date(date+'T00:00:00'); return {day:d.getDate(), month:new Intl.DateTimeFormat('id-ID',{month:'short'}).format(d).toUpperCase()}; };
function renderEntry(entry){const t=$('#entry-template').content.cloneNode(true),p=dayParts(entry.date);t.querySelector('.entry-date strong').textContent=p.day;t.querySelector('.entry-date span').textContent=p.month;t.querySelector('.category-badge').textContent=entry.category;t.querySelector('.read-time').textContent=formatDate(entry.date);t.querySelector('h3').textContent=entry.title;t.querySelector('.entry-content>p').textContent=entry.body;t.querySelector('.tags').innerHTML=(entry.tags||[]).map(x=>`<span>#${x}</span>`).join('');t.querySelector('.entry-note').textContent=entry.lesson?`✦ ${entry.lesson}`:'';t.querySelector('.delete-entry').dataset.id=entry.id;return t}
function refresh(){entries.sort((a,b)=>b.date.localeCompare(a.date));$('#entry-count').textContent=entries.filter(e=>e.date.startsWith('2026-09')).length;$('#focus-count').textContent=new Set(entries.filter(e=>e.date.startsWith('2026-09')).map(e=>e.category)).size;$('#wins-count').textContent=entries.filter(e=>e.win).length;$('#lesson-count').textContent=entries.filter(e=>e.lesson).length;$('#recent-entries').replaceChildren(...entries.slice(0,3).map(renderEntry));$('#goal-list').innerHTML=goals.map(g=>`<div class="goal-item"><div><span>${g.title}</span><span>${g.progress}%</span></div><p>${g.note}</p><div class="progress"><span style="width:${g.progress}%"></span></div></div>`).join('');const september=entries.filter(e=>e.date.startsWith('2026-09'));const cats=[...new Set(september.map(e=>e.category))];$('#monthly-summary').textContent=`September adalah bulan ketika Anda mulai beralih dari sekadar mengikuti project menjadi mengambil kepemilikan atas pekerjaan. Fokus terbesar ada pada ${cats.join(' dan ')||'refleksi'}: memahami TISCO Task Reminder, menyatukan dokumen, serta membangun cara kerja PIC yang lebih rapi. Benang merahnya adalah belajar mengubah hal yang belum jelas menjadi catatan, pertanyaan, dan langkah berikutnya.`;$('#summary-themes').innerHTML=['Project ownership','TISCO Task Reminder','Requirement clarity','Learning by doing'].map(x=>`<span>${x}</span>`).join('');renderTimeline();}
function renderTimeline(){const q=$('#search-input').value.toLowerCase(),cat=$('#category-filter').value,period=$('#period-filter').value;const filtered=entries.filter(e=>(cat==='all'||e.category===cat)&&(!period||period==='all'||e.date.startsWith(period))&&(!q||`${e.title} ${e.body} ${(e.tags||[]).join(' ')} ${e.lesson||''}`.toLowerCase().includes(q)));const list=$('#timeline-list');list.replaceChildren(...filtered.map(renderEntry));if(!filtered.length)list.innerHTML='<p style="color:#718098;padding:20px 0">Belum ada catatan yang cocok.</p>'}
function setView(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${view}-view`));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#view-title').textContent=view==='dashboard'?'Halo, Farrell.':view==='timeline'?'Jejak yang tersimpan.':view==='inbox'?'Percakapan yang layak diingat.':'Ruang untuk mengingat.';window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.viewLink)));document.querySelectorAll('[data-open-entry]').forEach(b=>b.addEventListener('click',()=>setView('entry')));$('#search-input').addEventListener('input',renderTimeline);$('#category-filter').addEventListener('change',renderTimeline);$('#period-filter').addEventListener('change',renderTimeline);
$('#entry-form').addEventListener('submit',e=>{e.preventDefault();const tags=$('#entry-tags').value.split(',').map(x=>x.trim()).filter(Boolean);entries.unshift({id:`entry-${Date.now()}`,date:$('#entry-date').value,category:$('#entry-category').value,title:$('#entry-title').value.trim(),body:$('#entry-body').value.trim(),tags,win:$('#entry-win').value.trim(),lesson:$('#entry-lesson').value.trim()});localStorage.setItem('farrell-journal-entries',JSON.stringify(entries));e.target.reset();$('#entry-date').value=new Date().toISOString().slice(0,10);$('#save-status').textContent='Entry tersimpan di perangkat ini.';refresh();setTimeout(()=>$('#save-status').textContent='',4000)});
$('#export-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({owner:'Farrell',exportedAt:new Date().toISOString(),entries,goals},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='jurnal-farrell-export.json';a.click();URL.revokeObjectURL(url)});
const categorySelect=$('#category-filter');[...new Set(entries.map(e=>e.category))].forEach(c=>categorySelect.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));refresh();
const renderInsightItems = (target, items) => $(target).innerHTML = items.map(([title,body]) => `<div class="insight-item"><strong>${title}</strong><p>${body}</p></div>`).join('');
renderInsightItems('#built-list', [
  ['Roblox MCP Trading System', 'Konsep inventory, analisis harga/volume, strategi, ROI, paper trading, website, dan AI/MCP—dimulai dengan akses read-only.'],
  ['AI Solar/PLTS Calculator', 'Gagasan membaca tagihan, menghitung kebutuhan dan payback PLTS, lalu membuat proposal otomatis.'],
  ['Life Journal', 'Ruang untuk menangkap progress, keputusan, dan pembelajaran Anda dari waktu ke waktu.']
]);
renderInsightItems('#learned-list', [
  ['Membangun sistem dengan AI', 'AI menjadi bernilai saat terhubung ke API, database, backend, dan alur kerja.'],
  ['Product & project thinking', 'Requirement, scope, MoM, FSD, dependency, dan Gantt Chart adalah alat menjaga kejelasan.'],
  ['Finance & risk', 'Debt, yield, valuation, FCF, ROIC, breakout, dan invalidation membantu melihat risiko lebih sadar.'],
  ['Berkolaborasi & bereksperimen', 'Linear, Figma, GitHub, serta hackathon adalah pintu untuk membangun bersama orang lain.']
]);
$('#gap-list').innerHTML = [
  ['UGC: bukti & angka', 'Catat inventory, modal Robux, harga beli/jual, volume, holding period, dan hasil paper trading agar strategi bisa diuji.'],
  ['Dari konsep ke prototipe', 'Pilih satu versi paling kecil untuk dibuat dulu—misalnya tracker inventory UGC read-only atau kalkulator PLTS sederhana.'],
  ['Sistem belajar', 'Buat ritme mingguan: apa yang dipelajari, diuji, selesai, dan yang perlu ditanyakan lagi ke ChatGPT atau mentor.'],
  ['Validasi pasar', 'Sebelum membangun besar, bicaralah dengan calon pengguna dan uji apakah masalahnya benar-benar mereka rasakan.'],
  ['Kolaborasi', 'Lanjutkan mencari teammate/mentor dan latih cara menjelaskan ide secara singkat dan konkret.'],
  ['Jurnal yang jujur', 'Tambahkan failures, keputusan yang belum pasti, serta angka bisnis/money supaya rangkuman masa depan lebih nyata.']
].map(([title,body], index) => `<div class="gap-item"><span>0${index+1}</span><h4>${title}</h4><p>${body}</p></div>`).join('');
let inboxDraft = null;
const detect = (text, words) => words.some(word => text.toLowerCase().includes(word));
$('#create-draft').addEventListener('click', () => {
  const text = $('#inbox-text').value.trim();
  if (!text) { $('#inbox-text').focus(); return; }
  const category = detect(text,['roblox','ugc','robux','trading','profit','bisnis','plts']) ? 'Business' : detect(text,['tisco','fsd','mom','gantt','magang','kuliah','project']) ? 'Work & Study' : 'Reflection';
  const tags = [['roblox','Roblox UGC'],['ugc','UGC'],['tisco','TISCO'],['ai','AI'],['mcp','MCP'],['api','API'],['database','database'],['plts','PLTS'],['finance','finance'],['gantt','project management']].filter(([word])=>text.toLowerCase().includes(word)).map(([,tag])=>tag);
  const topic = tags[0] || (category === 'Work & Study' ? 'project dan pembelajaran' : category === 'Business' ? 'ide bisnis' : 'refleksi');
  inboxDraft = {id:`entry-${Date.now()}`,date:new Date().toISOString().slice(0,10),category,title:`Catatan dari percakapan: ${topic}`,body:text.length > 640 ? `${text.slice(0,637).trim()}...` : text,tags,win:'',lesson:'Hal yang dibahas layak dijadikan langkah atau pertanyaan berikutnya.'};
  $('#draft-empty').hidden=true;$('#draft-result').hidden=false;$('#draft-category').textContent=category;$('#draft-title').textContent=inboxDraft.title;$('#draft-body').textContent=inboxDraft.body;$('#draft-tags').innerHTML=tags.map(tag=>`<span>#${tag}</span>`).join('');$('#draft-win').value='';$('#draft-lesson').value=inboxDraft.lesson;
});
$('#discard-draft').addEventListener('click', () => { inboxDraft=null;$('#draft-result').hidden=true;$('#draft-empty').hidden=false; });
$('#save-draft').addEventListener('click', () => { if(!inboxDraft)return; inboxDraft.win=$('#draft-win').value.trim();inboxDraft.lesson=$('#draft-lesson').value.trim();entries.unshift(inboxDraft);localStorage.setItem('farrell-journal-entries',JSON.stringify(entries));refresh();$('#inbox-text').value='';$('#draft-result').hidden=true;$('#draft-empty').hidden=false;inboxDraft=null;setView('timeline'); });
document.addEventListener('click', event => { const button = event.target.closest('.delete-entry'); if (!button) return; const entry = entries.find(item => item.id === button.dataset.id); if (!entry) return; if (!confirm(`Hapus entry “${entry.title}”?`)) return; entries = entries.filter(item => item.id !== entry.id); localStorage.setItem('farrell-journal-entries', JSON.stringify(entries)); refresh(); });

const supabaseClient = window.supabase.createClient(window.LIFE_JOURNAL_SUPABASE.url, window.LIFE_JOURNAL_SUPABASE.publishableKey);
let wantsSignup = false;
const authMessage = message => $('#auth-message').textContent = message;
async function showSession(){ const {data:{session}} = await supabaseClient.auth.getSession(); if(session){ $('#auth-screen').hidden=true; } }
$('#signup-button').addEventListener('click', () => { wantsSignup=!wantsSignup; $('#signup-button').textContent=wantsSignup?'Sudah punya akun? Masuk':'Belum punya akun? Daftar'; $('#auth-form button[type="submit"]').textContent=wantsSignup?'Buat akun':'Masuk'; authMessage(''); });
$('#auth-form').addEventListener('submit', async event => { event.preventDefault(); const email=$('#auth-email').value,password=$('#auth-password').value; authMessage('Memproses…'); const result=wantsSignup ? await supabaseClient.auth.signUp({email,password}) : await supabaseClient.auth.signInWithPassword({email,password}); if(result.error){authMessage(result.error.message);return;} if(wantsSignup && !result.data.session){authMessage('Akun dibuat. Periksa email untuk konfirmasi, lalu masuk.');return;} $('#auth-screen').hidden=true; });
showSession();

